/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/connect`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/madhab`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/nisab`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/calculate`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/hawl`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/overview`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/connect`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/madhab`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/nisab`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/calculate`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/hawl`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/overview`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/onboarding/connect${`?${string}` | `#${string}` | ''}` | `/onboarding/madhab${`?${string}` | `#${string}` | ''}` | `/onboarding/nisab${`?${string}` | `#${string}` | ''}` | `/tabs/calculate${`?${string}` | `#${string}` | ''}` | `/tabs/hawl${`?${string}` | `#${string}` | ''}` | `/tabs/overview${`?${string}` | `#${string}` | ''}` | `/tabs/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/connect`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/madhab`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/nisab`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/calculate`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/hawl`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/overview`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
